### ISSUE TITLE
What am I paying for? The constant bugs, IDE's slowing down after your plugin!!!!

### ISSUE THREAD

**Issue by legion-zver** [beansoft/react-native-console#52]
java.lang.StackOverflowError
	at java.base/java.io.File.list(File.java:1136)
	at java.base/java.io.File.listFiles(File.java:1300)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
	at com.github.beansoftapp.reatnative.idea.utils.D.Ă(Unknown Source)
...

**Comment by beansoft** [comment]
@legion-zver Could you please provide addtional info such as Plugin version, IDEA version and better a project structure screenshot for me? First I'm sorry for that, but I need more info on how to fix it. You paid so I'll provide support for fix bugs at a quick response.

**Comment by beansoft** [comment]
I've create a patched version which fixs this issue, please have a try.  Download and install it locally:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=99260

**Comment by beansoft** [comment]
reproduced when there is no file with extension in directly:

	at java.base/java.io.File.list(File.java:1134)
	at java.base/java.io.File.listFiles(File.java:1301)
	at com.github.beansoftapp.reatnative.idea.utils.RNPathUtil.getIosFolderContainsExt(RNPathUtil.java:340)
	at com.github.beansoftapp.reatnative.idea.utils.RNPathUtil.getIosFolderContainsExt(RNPathUtil.java:352)

**Comment by beansoft** [comment]
@legion-zver I've create a patched version which fixs this issue, please have a try. Download and install it locally:

https://plugins.jetbrains.com/plugin/download?rel=true&updateId=99261

**Comment by beansoft** [comment]
It's released in 2.2.16 for WebStorm 2020.1 and 2020.3.2 EAP for WebStorm 2020.2, please upgrade in your WebStorm had have a try.

**Comment by legion-zver** [comment]
@beansoft great! Thanks!
