### ISSUE TITLE
svg icon preview error: Image should be square

### ISSUE THREAD

**Issue by beansoft** [beansoft/react-native-console#59]
java.lang.IllegalArgumentException: Image should be square.
	at lermitage.intellij.iconviewer.CustomIconLoader.scaleImage(CustomIconLoader.java:116)
	at lermitage.intellij.iconviewer.CustomIconLoader.loadFromVirtualFile(CustomIconLoader.java:46)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewSvgImage(ImageIconProvider.java:167)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:78)
	at com.github.beansoftapp.reatnative.idea.project.RNIconProvider.getIcon(RNIconProvider.java:45)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)

**Comment by beansoft** [comment]
After check the source and now fixed this issue, all icons displays should as clean as original retina icons.
Will released in 2021.1.0
