### ISSUE TITLE
Load Bad SVG crash issue

### ISSUE THREAD

**Issue by beansoft** [beansoft/react-native-console#65]
java.lang.IllegalArgumentException: Could not load image properly.
	at lermitage.intellij.iconviewer.CustomIconLoader.loadFromVirtualFile(CustomIconLoader.java:79)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewSvgImage(ImageIconProvider.java:173)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:77)
	at com.github.beansoftapp.reatnative.idea.project.RNIconProvider.getIcon(RNIconProvider.java:45)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)

**Comment by beansoft** [comment]
fixed in 2021.1.7.3
