### ISSUE TITLE
Synchronous execution on EDT

### ISSUE THREAD

**Issue by beansoft** [beansoft/react-native-console#66]
java.lang.Throwable: Synchronous execution on EDT: /Users/beansoft/Documents/Java/android-sdk-macosx/emulator/emulator -list-avds, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:172)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:110)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:39)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:55)
	at com.intellij.execution.util.ExecUtil.execAndGetOutput(ExecUtil.kt:89)
	at com.github.beansoftapp.reatnative.idea.utils.android.AVDList.getAvdList(AVDList.java:22)

**Comment by beansoft** [comment]
similiar to issue https://github.com/flutter/flutter-intellij/issues/5012

**Comment by beansoft** [comment]
fixed in 2021.2.0
