### ISSUE TITLE
Getting IDE crash notification in IntelliJ IDEA 2021.1.1. 

### ISSUE THREAD

**Issue by cameronolivier** [beansoft/react-native-console#68]
java.lang.NullPointerException
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.OpenInAndroidStudioAction.findStudioProjectFile(OpenInAndroidStudioAction.java:247)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.OpenInAndroidStudioAction.findProjectFile(OpenInAndroidStudioAction.java:174)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.OpenInAndroidStudioAction.updatePresentation(OpenInAndroidStudioAction.java:125)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.OpenInAndroidStudioAction.update(OpenInAndroidStudioAction.java:48)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.NativeEditorNotificationProvider$NativeEditorActionsPanel.<init>(NativeEditorNotificationProvider.java:137)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.NativeEditorNotificationProvider.createPanelForAction(NativeEditorNotificationProvider.java:80)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.NativeEditorNotificationProvider.createPanelForFile(NativeEditorNotificationProvider.java:73)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:65)
	at com.github.beansoftapp.reatnative.idea.actions.console.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:33)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:165)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$3(EditorNotificationsImpl.java:143)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by beansoft** [comment]
could you provide some extra info? i need to know the project structure and in which path it crashes.
