### ISSUE TITLE
Plugin error on Intellij IDEA 2023.3.1

### ISSUE THREAD

**Issue by dadangnh** [beansoft/react-native-console#77]
## What happened

Got an error when opening the IDE

## Version information

IntelliJ IDEA `2023.3.1` • React Native Console plugin `com.github.beansoftapp.reatnative.idea 2023.3.0`
## Exception

Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1

```
java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:58)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:54)
	at com.intellij.openapi.util.registry.Registry.getInstance(Registry.java:180)
	at com.intellij.openapi.util.registry.Registry.get(Registry.java:45)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:58)
	at beansoft.intellij.ui.ExperimentalUI.isNewUI(ExperimentalUI.java:19)
	at icons.PluginIcons.<clinit>(PluginIcons.java:28)
	at com.github.beansoftapp.reatnative.idea.actions.touchbar.ShowConsoleRefreshAnrdoidAction.<init>(ShowConsoleRefreshAnrdoidAction.java:24)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1383)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1392)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1377)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1400)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1733)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:323)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:314)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:375)
	at com.mallowigi.actions.OldToolbarAdder.executeAdd(OldToolbarAdder.kt:50)
	at com.mallowigi.actions.OldToolbarAdder.customize$lambda$0(OldToolbarAdder.kt:42)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1430)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:321)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by beansoft** [comment]
@dadangnh Please try to see if this new version (install from disk please) fixed the problem:
[react-native-console.zip](https://github.com/beansoft/react-native-console/files/13716290/react-native-console.zip)

**Comment by dadangnh** [comment]
Hi @beansoft , I've tried the updated plugin, the error is gone. Thanks

**Comment by beansoft** [comment]
will upload an update, but as the plugin team is on holiday, should be available publicly after 1 or 2 weeks.
