### ISSUE TITLE
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED

### ISSUE THREAD

**Issue by beansoft** [beansoft/react-native-console#78]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2023.3.1` • React Native Console plugin `com.github.beansoftapp.reatnative.idea 2023.3.0`
## Exception

Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1

```
java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:58)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:54)
	at com.intellij.openapi.util.registry.Registry.getInstance(Registry.java:180)
	at com.intellij.openapi.util.registry.Registry.get(Registry.java:45)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:58)
	at beansoft.intellij.ui.ExperimentalUI.isNewUI(ExperimentalUI.java:19)
	at icons.PluginIcons.<clinit>(PluginIcons.java:28)
	at com.github.beansoftapp.reatnative.idea.actions.newfile.CreateReactNativeComponentFileAction.<init>(CreateReactNativeComponentFileAction.java:29)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1383)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1392)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1377)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1400)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1733)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:323)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:314)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:375)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.ide.actions.WeighingActionGroup.getChildren(WeighingActionGroup.java:44)
	at com.intellij.ide.actions.WeighingNewActionGroup.getChildren(WeighingNewActionGroup.java:11)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.getActions(ActionsTreeUtil.java:743)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:232)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:239)
	at com.intellij.openapi.keymap.impl.ui.ActionsTreeUtil.createGroup(ActionsTreeUtil.java:189)
	at com.intellij.ide.ui.customization.ActionUrl.readExternal(ActionUrl.java:133)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:227)
	at com.intellij.ide.ui.customization.CustomActionsSchema.loadState(CustomActionsSchema.kt:61)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:490)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:409)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:131)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:931)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:41)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:993)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$preloadCriticalServices$2$4.invokeSuspend(appServicePreloading.kt:211)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by sprocki** [comment]
Launching IntelliJ for the first time on WSL (win11), Ubuntu 24.04 - same exception:
```
:/tmp/idea-IU-253.30387.90$ bin/idea
Feb 02, 2026 3:41:46 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
2026-02-02 15:41:48,607 [   1771]   WARN - #c.i.i.p.PluginManager - Problems found loading plugins:
  Plugin 'AOP Pointcut Language' (com.intellij.aop) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Dev Containers' (org.jetbrains.plugins.docker.gateway) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Cron Expressions' (com.intellij.cron) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'CSS' (com.intellij.css) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Flyway' (com.intellij.flyway) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'FreeMarker' (com.intellij.freemarker) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Remote Development Gateway' (com.jetbrains.gateway) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Hibernate' (com.intellij.hibernate) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Shared Project Indexes' (intellij.indexing.shared) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'JavaFX' (org.jetbrains.plugins.javaFX) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Application Servers' (com.intellij.javaee.app.servers.integration) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'WildFly' (JBoss) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Tomcat and TomEE' (Tomcat) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Bean Validation' (com.intellij.beanValidation) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Contexts and Dependency Injection (CDI)' (com.intellij.cdi) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Messaging (JMS)' (com.intellij.javaee.extensions) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Data' (com.intellij.javaee.jakarta.data) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: RESTful Web Services (JAX-RS)' (com.jetbrains.restWebServices) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Persistence (JPA)' (com.intellij.javaee.jpa) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Server Pages (JSP)' (com.intellij.jsp) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'JVM Persistence Frameworks' (com.intellij.persistence) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Jakarta EE: Web/Servlets' (com.intellij.javaee.web) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'JavaScript and TypeScript' (JavaScript) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Liquibase' (com.intellij.liquibase) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Micronaut' (com.intellij.micronaut) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Node.js Remote Interpreter' (org.jetbrains.plugins.node-remote-interpreter) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Quarkus' (com.intellij.quarkus) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'SSH Remote Run' (org.jetbrains.plugins.remote-run) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Cloud' (com.intellij.spring.cloud) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Boot' (com.intellij.spring.boot) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Data' (com.intellij.spring.data) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Integration Patterns' (com.intellij.spring.integration) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Messaging' (com.intellij.spring.messaging) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Modulith' (com.intellij.spring.modulith) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Web' (com.intellij.spring.mvc) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Spring Security' (com.intellij.spring.security) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Tailwind CSS' (com.intellij.tailwindcss) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Time Tracking' (com.intellij.tasks.timeTracking) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Apache Velocity' (com.intellij.velocity) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'FTP/SFTP/WebDAV Connectivity' (com.jetbrains.plugins.webDeployment) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Refactor-X' (Refactor-X) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'React' (com.intellij.react) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Stylelint' (com.intellij.stylelint) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Vite' (intellij.vitejs) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Less' (org.jetbrains.plugins.less) has dependency on 'CSS' which cannot be loaded
  Plugin 'PostCSS' (org.intellij.plugins.postcss) has dependency on 'CSS' which cannot be loaded
  Plugin 'Webpack' (intellij.webpack) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Vue.js' (org.jetbrains.plugins.vue) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'TSLint' (tslint) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Sass' (org.jetbrains.plugins.sass) has dependency on 'CSS' which cannot be loaded
  Plugin 'In-Editor Performance Hints' (com.intellij.LineProfiler) requires plugin with id=com.intellij.modules.ultimate to be enabled
  Plugin 'Node.js' (NodeJS) has dependency on 'com.intellij.modules.javascript' which is not installed
  Plugin 'Styled Components & Styled JSX' (com.deadlock.scsyntax) has dependency on 'CSS' which cannot be loaded
  Plugin 'Polymer & Web Components' (com.intellij.plugins.webcomponents) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Prettier' (intellij.prettierJS) has dependency on 'com.intellij.modules.javascript' which is not installed
  Plugin 'Next.js' (intellij.nextjs) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Reverse Engineering' (com.intellij.javaee.reverseEngineering) has dependency on 'Liquibase' which cannot be loaded
  Plugin 'Karma' (Karma) has dependency on 'com.intellij.modules.javascript' which is not installed
  Plugin 'JavaScript Intention Power Pack' (JSIntentionPowerPack) has dependency on 'JavaScript and TypeScript' which cannot be loaded
  Plugin 'Angular' (AngularJS) has dependency on 'JavaScript and TypeScript' which cannot be loaded
2026-02-02 15:41:49,606 [   2770]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - resource not found: colorSchemes/SqlDefault.xml
2026-02-02 15:41:49,627 [   2791]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - resource not found: colorSchemes/SqlDarcula.xml
2026-02-02 15:41:50,593 [   3757]   WARN - #c.i.s.c.i.StationSocketConnectionLoop - Discovery connection failed with NoSuchFileException (/run/user/1000/jb.station.sock)
2026-02-02 15:41:51,502 [   4666] SEVERE - #c.i.d.LoadingState - Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1


java.lang.Throwable
        at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
        at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
        at com.intellij.openapi.util.registry.Registry$Companion.getInstance(Registry.kt:182)
        at com.intellij.openapi.util.registry.Registry$Companion.is(Registry.kt:89)
        at com.intellij.platform.vcs.impl.shared.RdLocalChanges.isEnabled(RdLocalChanges.kt:10)
        at com.intellij.platform.vcs.backend.split.actions.VcsBackendTransferableKeysRule.uiDataSnapshot(VcsBackendTransferableKeysRule.kt:32)
        at com.intellij.openapi.actionSystem.impl.PreCachedDataContextKt.runSnapshotRules$lambda$0(PreCachedDataContext.kt:427)
        at com.intellij.openapi.actionSystem.impl.PreCachedDataContextKt.runSnapshotRules$lambda$1(PreCachedDataContext.kt:421)
        at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:61)
        at com.intellij.openapi.actionSystem.UiDataRule$Companion.forEachRule(UiDataProvider.kt:112)
        at com.intellij.openapi.actionSystem.impl.PreCachedDataContextKt.runSnapshotRules(PreCachedDataContext.kt:421)
        at com.intellij.openapi.actionSystem.impl.PreCachedDataContextKt.access$runSnapshotRules(PreCachedDataContext.kt:1)
        at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.<init>(PreCachedDataContext.kt:116)
        at com.intellij.openapi.actionSystem.impl.Utils.createAsyncDataContext(Utils.kt:174)
        at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.createUiDataContext(IdeUiServiceImpl.java:82)
        at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.kt:206)
        at com.intellij.openapi.wm.impl.WindowWatcher.propertyChange(WindowWatcher.java:70)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
        at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1491)
        at java.desktop/java.awt.KeyboardFocusManager.setGlobalFocusedWindow(KeyboardFocusManager.java:882)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:451)
        at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent$lambda$0(IdeKeyboardFocusManager.kt:49)
        at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent$lambda$1(IdeKeyboardFocusManager.kt:55)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1051)
        at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.kt:55)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4926)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2823)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4877)
        at java.desktop/sun.awt.X11.XWindow$1.run(XWindow.java:444)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:300)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:935)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.lambda$show$14(DialogWrapperPeerImpl.java:510)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.lambda$show$7(DialogWrapperPeerImpl.java:458)
        at com.intellij.concurrency.ThreadContext.resetThreadContext(threadContext.kt:294)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.lambda$show$8(DialogWrapperPeerImpl.java:457)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:501)
        at com.intellij.openapi.ui.DialogWrapper.lambda$doShow$16(DialogWrapper.java:1823)
        at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
        at com.intellij.openapi.application.impl.AppImplKt$rethrowCheckedExceptions$2.invoke(appImpl.kt:126)
        at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.doRunWriteIntentReadAction(NestedLocksThreadingSupport.kt:736)
        at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runPreventiveWriteIntentReadAction(NestedLocksThreadingSupport.kt:710)
        at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteIntentReadAction(NestedLocksThreadingSupport.kt:664)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:1185)
        at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
        at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1822)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1770)
        at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1784)
        at com.intellij.ide.gdpr.AgreementUiBuilder.build$intellij_platform_ide_impl(AgreementUi.kt:157)
        at com.intellij.ide.gdpr.AgreementUiKt.showAgreementUi(AgreementUi.kt:33)
        at com.intellij.ide.gdpr.Agreements.showEndUserAndDataSharingAgreements(Agreements.kt:27)
        at com.intellij.platform.ide.bootstrap.EuaKt$prepareShowEuaIfNeededTask$2.invokeSuspend$lambda$0(eua.kt:73)
        at com.intellij.platform.ide.bootstrap.EuaKt$prepareShowEuaIfNeededTask$prepareAndExecuteInEdt$2$1.invokeSuspend(eua.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:300)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2026-02-02 15:41:51,513 [   4677] SEVERE - #c.i.d.LoadingState - IntelliJ IDEA 2025.3.2  Build #IU-253.30387.90
2026-02-02 15:41:51,513 [   4677] SEVERE - #c.i.d.LoadingState - JDK: 21.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2026-02-02 15:41:51,513 [   4677] SEVERE - #c.i.d.LoadingState - OS: Linux
2026-02-02 15:41:51,514 [   4678] SEVERE - #c.i.d.LoadingState - Last Action:
2026-02-02 15:42:22,287 [  35451]   WARN - #c.i.l.u.p.AIPromoWindowAdvisor - Verdict calculation took too long
^C2026-02-02 15:43:02,948 [  76112]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 130
2026-02-02 15:43:02,960 [  76124] SEVERE - #c.i.d.LoadingState - Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 2


java.lang.Throwable
        at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
        at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
        at com.intellij.openapi.util.registry.Registry$Companion.getInstance(Registry.kt:182)
        at com.intellij.openapi.util.registry.Registry$Companion.intValue(Registry.kt:107)
        at com.intellij.openapi.util.registry.Registry.intValue(Registry.kt)
        at com.intellij.util.indexing.FileBasedIndexImpl.performShutdown(FileBasedIndexImpl.java:703)
        at com.intellij.util.indexing.FileBasedIndexImpl$ShutDownIndexesTask.run(FileBasedIndexImpl.java:1317)
        at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:77)
        at com.intellij.openapi.util.ShutDownTracker.lambda$new$0(ShutDownTracker.java:42)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2026-02-02 15:43:02,967 [  76131] SEVERE - #c.i.d.LoadingState - IntelliJ IDEA 2025.3.2  Build #IU-253.30387.90
2026-02-02 15:43:02,968 [  76132] SEVERE - #c.i.d.LoadingState - JDK: 21.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2026-02-02 15:43:02,968 [  76132] SEVERE - #c.i.d.LoadingState - OS: Linux
2026-02-02 15:43:02,969 [  76133] SEVERE - #c.i.d.LoadingState - Last Action:
```

**Comment by beansoft** [comment]
My exception is similar to https://youtrack.jetbrains.com/issue/IJPL-1966/LoadingState-exception-should-be-called-at-least-in-the-state-COMPONENTSLOADED-the-current-state-is . However, yours does not appear to be related to my plugin, as the stack trace indicates an issue with the IDEA built-in JavaScript plugin. Is the IDE license not loaded? I'm not sure.

I've tried WSLG this morning, and it works fine:
```
sudo snap install intellij-idea --channel=2025.3/stable --classic
intellij-idea
```

Ref this article for more details: https://youtrack.jetbrains.com/articles/SUPPORT-A-847/How-to-install-and-run-IDEA-on-Windows-using-WSLG
